#include "../include/alttab.hpp"
#include <sol/sol.hpp>
#include <iostream>
#include <mutex>

extern sol::state *g_lua;
extern std::mutex g_lua_mutex;

HHOOK g_keyboard_hook = NULL;
bool g_alttab_active = false;

// Low-level keyboard hook callback
LRESULT CALLBACK KeyboardProc(int nCode, WPARAM wParam, LPARAM lParam) {
  if (nCode == HC_ACTION) {
    KBDLLHOOKSTRUCT *p = reinterpret_cast<KBDLLHOOKSTRUCT*>(lParam);

    // CRITICAL: Ignore synthetic keys generated by our own focus_window bypasses
    if (p->flags & LLKHF_INJECTED) {
      return CallNextHookEx(g_keyboard_hook, nCode, wParam, lParam);
    }

    bool alt_is_down = (p->flags & LLKHF_ALTDOWN) || (GetKeyState(VK_MENU) & 0x8000);

    // Handle Alt + Tab press
    if (p->vkCode == VK_TAB && alt_is_down) {
      if (wParam == WM_SYSKEYDOWN || wParam == WM_KEYDOWN) {
        g_alttab_active = true;

        if (g_lua) {
          std::unique_lock<std::mutex> lock(g_lua_mutex, std::try_to_lock);
          if (lock.owns_lock()) {
            try {
              sol::protected_function alttab_func = (*g_lua)["HyprWin"]["on_alttab_action"];
              if (alttab_func.valid()) {
                bool shift_is_down = (GetKeyState(VK_SHIFT) & 0x8000) != 0;
                auto result = alttab_func(shift_is_down ? "prev" : "next");
                if (!result.valid()) {
                  sol::error err = result;
                  std::cerr << "[AltTab] Lua Error: " << err.what() << std::endl;
                }
              }
            } catch (const std::exception& e) {
              std::cerr << "[AltTab] Exception: " << e.what() << std::endl;
            }
          }
        }
        return 1; // Intercept and block default Windows Alt+Tab dialog
      }
    }

    // Handle Alt key release to commit selection
    if ((p->vkCode == VK_MENU || p->vkCode == VK_LMENU || p->vkCode == VK_RMENU) && g_alttab_active) {
      if (wParam == WM_KEYUP || wParam == WM_SYSKEYUP) {
        g_alttab_active = false;

        if (g_lua) {
          std::unique_lock<std::mutex> lock(g_lua_mutex, std::try_to_lock);
          if (lock.owns_lock()) {
            try {
              sol::protected_function alttab_func = (*g_lua)["HyprWin"]["on_alttab_action"];
              if (alttab_func.valid()) {
                auto result = alttab_func("commit");
                if (!result.valid()) {
                  sol::error err = result;
                  std::cerr << "[AltTab] Commit Lua Error: " << err.what() << std::endl;
                }
              }
            } catch (const std::exception& e) {
              std::cerr << "[AltTab] Commit Exception: " << e.what() << std::endl;
            }
          }
        }
      }
    }
  }
  return CallNextHookEx(g_keyboard_hook, nCode, wParam, lParam);
}

bool InitializeAltTabHook() {
  g_keyboard_hook = SetWindowsHookEx(WH_KEYBOARD_LL, KeyboardProc, GetModuleHandle(NULL), 0);
  return g_keyboard_hook != NULL;
}

void CleanupAltTabHook() {
  if (g_keyboard_hook) {
    UnhookWindowsHookEx(g_keyboard_hook);
    g_keyboard_hook = NULL;
  }
  g_alttab_active = false;
}