require("hyprland_modules/Monitors")
require("hyprland_modules/Input")
require("hyprland_modules/Autostart")
require("hyprland_modules/Generals")
require("hyprland_modules/Misc")
require("hyprland_modules/Gestures")
require("hyprland_modules/Keybinds")
require("hyprland_modules/Rules")
require("hyprland_modules/Animations")
-- require("hyprland_modules/Animations_End4")
require("hyprland_modules/Layouts")
require("hyprland_modules/Decorations")
